# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false


## Environment Properties

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)

forge_version=47.4.0
forge_version_range=[47,)
loader_version_range=[47,)

# Deps
geckolib_version=4.3
geckolib_version_range=[4.2,)

# The mapping channel to use for mappings.
# The default set of supported mapping channels are ["official", "snapshot", "snapshot_nodoc", "stable", "stable_nodoc"].
# Additional mapping channels can be registered through the "channelProviders" extension in a Gradle plugin.
#
# | Channel   | Version              |                                                                                |
# |-----------|----------------------|--------------------------------------------------------------------------------|
# | official  | MCVersion            | Official field/method names from Mojang mapping files                          |
# | parchment | YYYY.MM.DD-MCVersion | Open community-sourced parameter names and javadocs layered on top of official |
#
# Parchment is an unofficial project maintained by ParchmentMC, separate from Minecraft Forge.
# Additional setup is needed to use their mappings, see https://parchmentmc.org/docs/getting-started
mapping_channel=official
mapping_version=1.20.1


## Mod Properties

# Must match the String constant located in the main mod class annotated with @Mod.
mod_id=outofplacecraft
mod_name=Out-Of-Placecraft
# https://choosealicense.com/
mod_license=MIT
mod_version=2.0.0-dev

mod_group_id=ink.echol.outofplacecraft
mod_authors=Gyro, Yaodema, Alex Zhe Yinglet, Earth-Fury
mod_description=An Out Of Placers mod that allows you to play as a yinglet after being zatzhinged.\nAlso just adds clams generally.