modLoader="javafml"
loaderVersion="[36,)"
license="Licensed under the LGPL 3.0 and CC-BY-SA 4.0. See the included LICENSE file(s) for details."
issueTrackerURL="https://github.com/NotGyro/OutOfPlacecraft/issues" #optional

[[mods]]
modId="outofplacecraft"
version="${file.jarVersion}"
displayName="Out of Placecraft"
# https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="https://change.me.example.invalid/updates.json"
displayURL="https://github.com/NotGyro/OutOfPlacecraft"
#logoFile="examplemod.png"
#credits="Thanks for this example mod goes to Java" #optional
authors="See included AUTHORS file" #optional
description='''
An Out Of Placers mod that allows you to play as a yinglet after being zatzinged.
'''

[[dependencies.outofplacecraft]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.outofplacecraft]]
    modId="minecraft"
    mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"

[[dependencies.outofplacecraft]]
    modId="geckolib3"
    mandatory=true
    versionRange="[3.0.41,)"
    ordering="AFTER"
    side="BOTH" #Change this to client? Unsure.
